### ISSUE TITLE
Please add a license file.

### ISSUE THREAD

**Issue by unixorn** [lcrespom/oh-my-zsh-history-popup#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

**Comment by lcrespom** [comment]
Hello Joe,

I am still developing the plugin, but it's almost done. I will add a
license and a proper README.md file, then let you know when it's ready.

I will be very happy that my plugin is in the list :-).

Regards,
Luis.

**Comment by lcrespom** [comment]
Hello Joe,

The plugin is ready and fully usable, although there are some minor
improvements pending. I have added proper documentation and a license file.

Feedback is welcome.

Regards,
Luis.

**Comment by unixorn** [comment]
Thanks, adding it in https://github.com/unixorn/awesome-zsh-plugins/pull/842
